### ISSUE TITLE
Update From The Vault Exhibit List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1062]
Just would like to make a few updates to [the list of items in the From The Vault exhibit.](http://openvault.wgbh.org/collections/vault-from-the-vault)
Changes that need to be made are marked in **bold**.
**REMOVE LINK** = Remove link and text from the page
<B>CHANGE TITLE </B>= Keep the link, change the text listing
If there is no bold, no changes need to be made to the text or link

**REMOVE LINK-** The Negro and the American Promise
James Baldwin Interview
Malcolm X Interview
Martin Luther King Jr. Interview
Remembering James Brown at the Boston Garden, 1968
**REMOVE LINK-**James Brown Concert: 1 of 2
**REMOVE LINK-**James Brown Concert: 2 of 2
James Brown Speaks to the Crowd at the Boston Garden 
James Brown and Mayor Kevin White Address the Crowd at the Boston Garden
**REMOVE LINK-**Zoom Sample
Send In Your Zoom Ideas
**REMOVE LINK-**ZOOM
Here's How You Do It
**REMOVE LINK-**Perspectives
<B>CHANGE TITLE- </B>  The Advocates: Timothy Leary and Jerome Lettvin <B>CHANGE TO: </B> *LSD:  Lettvin Vs Leary*
**REMOVE LINK-**At Home
<B>CHANGE TITLE- </B>Bill Lee, Red Sox pitcher <B>CHANGE TO: </B>*At Home: Bill Lee, Red Sox Pitcher*
**REMOVE LINK-**Machine That Changed the World, The
**REMOVE LINK-**Paperback Computer, The
Steve Jobs Interview
Odetta Gordon performs "Give Me Your Hand"
**REMOVE LINK-**Say Brother: Odetta
Memories of Fenway Park: Jean Shepherd
**REMOVE LINK-**Dancing Disco
<B>CHANGE TITLE- </B>Disco Fashion <B>CHANGE TO: </B>*Dancing Disco: Episode 1: Disco Fashion*
<B>CHANGE TITLE- </B>Let's Dance! <B>CHANGE TO: </B>*Dancing Disco: Let's Dance!*
<B>CHANGE TITLE- </B>Triple Hustle <B>CHANGE TO: </B>*Dancing Disco: Triple Hustle*
First Patriots Day Intro
First Patriots Day
**REMOVE LINK-**Jean Shepherd
<B>CHANGE TITLE- </B>John Updike <B>CHANGE TO: </B>*At Home: John Updike*

**Comment by Muraszko** [comment]
Jobs link is here:
http://openvault.wgbh.org/catalog/7b7ae3-steve-jobs-interview
UOI_ID:
8b6275dd5d1c41416caa93058eacf71be17b7ae3

**Comment by afred** [comment]
fixed by #1200. @Muraszko, take a peek on [staging](http://openvault-staging.wgbh.org/collections/from-the-vault). If good, please close this ticket. thanks!
