### ISSUE TITLE
Combine Elizabeth Deane's Scholar Collections

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1110]
Elizabeth Deane will have around 13 scholar collections when they are all created.  Because she's the only owner with more than one collection, and all her articles are from "From the Vault iPad Articles" her collections need to not show up on the main scholar page.
So all that's on the scholar collection page from her should be ONE collection link from her that has all her articles within it.

**DONE WHEN**
A user of Open Vault clicks on Scholar Collections "Show All" and they see a link and description for "From the Vault iPad Articles".
If they click on that they are taken to another collection page that only displays a list of Scholar Collections written by Elizabeth Deane.

**Comment by afred** [comment]
@Muraszko what about the articles has to do with an iPad?

**Comment by afred** [comment]
@Muraszko also, do we have a little blurb to act as the collection summary?

**Comment by Muraszko** [comment]
@afred 
Better title?  **From The WGBH Vault Articles**

Blurb:
"This collection of articles highlights content from the WGBH Media Library and Archives that are of historical or cultural significance.  They were composed by longtime WGBH producer and writer, Elizabeth Deane."

Feel free to tweak if either don't sound right, thanks.

**Comment by afred** [comment]
word

**Comment by mccalluc** [comment]
Talked with Michael: We'll have the partial not output anything for Elizabeth Deane: Instead, she'll just get static html at the top of the page. If we have more authors authoring multiple articles, we can worry about that later.
