### ISSUE TITLE
Duplicate program records in Advocates (and maybe elsewhere)

### ISSUE THREAD

**Issue by afred** [afred/openvault#1130]
This may be covered by other duplication issues. But here's another example just in case it's different than the rest.

Searching for "should the president spend money" gives this result:
![image](https://cloud.githubusercontent.com/assets/1507490/5591126/e9bac600-9118-11e4-9b35-00102756e27d.png)

We expect 3 results, but we get 5 instead.
The three we expect are:
  * the MARS program record
  * the Artesia program record
  * the Artesia video record.

but it looks like both the Artesia and MARS program records got duped. Not sure why.

**done when**
  - [ ] we de-dupe the MARS program records. NOTE: that the MARS program we want to keep will probably be associated with a MARS Series record, while the other MARS program record may not.
  - [ ] we de-dupe the Artesia program records. NOTE: the Artesia program record we want is the one associated with the Artesia Video record. We don't need the other one.

**Comment by Muraszko** [comment]
@afred 
I think re-ingest fixed this too.  Close if you agree.

**Comment by afred** [comment]
yep.
