### ISSUE TITLE
Missing transcripts

### ISSUE THREAD

**Issue by afred** [afred/openvault#1132]
**done when**
The following TEI xml files are accounted for:
  * transcript_Daniel_Ellsberg1_Interview_Merged_SMIL.xml
  * transcript_Daniel_Ellsberg2_Interview_Merged_SMIL.xml
  * transcript_benoit_smil.xml
  * transcript_simpson-jones_smil.xml
  * transcript_taylor_reverses.xml
  * transcript_tong_teng_smil.xml

**Comment by afred** [comment]
@Muraszko i found a few transcripts that had been ingested, but were missing the TEI xml of the actual transcript text. Any ideas?

**Comment by Muraszko** [comment]
@afred 
Those Daniel Ellsberg ones shouldn't be on Open Vault.  We never cleared the interview, if you look at the record page for them:
http://openvault.wgbh.org/catalog/openvault:47768
"Note Media not to be released to Open Vault"

Looking at their records in findam, all of those transcript files have "Not to be released to Open Vault" actually.
So you can probably close this.

**Comment by afred** [comment]
ok
