### ISSUE TITLE
March on Washington Exhibit Page

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1134]
Made a ticket for this because its exhibit page is slightly different than other ones.  The exhibit page has no no video or programs, it's composed of audio and photographs.
It should have tabs or links for:
-ERN's coverage of the March on Washington for Jobs and Freedom
-Revisiting the March on Washington
-Photographs

**Comment by mccalluc** [comment]
It looks like 10 Audios are connected to a Series with this pbcore:
```xml
<pbcoreDescriptionDocument>
    <pbcoreIdentifier source="UOI_ID">27afb5495dec3586bbcb00e19f6c2841745a248d</pbcoreIdentifier>
    <pbcoreIdentifier source="IMPORT_ID">159430.0</pbcoreIdentifier>
    <pbcoreTitle titleType="Series">March on Washington</pbcoreTitle>
    <pbcoreDescription descriptionType="Summary5">The Educational Radio Network / ERN's coverage of the March on Washington for Jobs and Freedom.</pbcoreDescription>
```
which is currently at http://openvault.wgbh.org/catalog/5a248d-march-on-washington

- Should more Audio be connected to this?
- Should Images be connected to this? (Currently none are.)
- Could it be reslugged with `march-march-on-washington`?

**Comment by mccalluc** [comment]
... but these [18 images](http://openvault.wgbh.org/catalog?f[media_sim][]=Image&q=march+on+washington) are unrelated to any other asset: Should they be?

**Comment by Muraszko** [comment]
@mccalluc 
Yeah, you could add the programs from the MARS Series "March on Washington for Jobs and Freedom". Looks like 17 Programs.
```
Martin Luther King, Jr.: I Have a Dream Speech
Panel Discussion on the Implications of the Freedom March [1 of 2]
George Geesey Introduction
Interviews with Participants; Music from Stage
President John F. Kennedy Speech on the Upcoming March
March Reporting
Celebrity Participation in the March on Washington
March Begins
Roy Wilkins Addresses the Crowd
Bayard Rustin Reads the Demands of the March
Crowd Disperses From the Mall
Reflections on the March
News Bulletin and March Overview
March Highlights [1 of 2]
March Highlights [2 of 2]
ERN Reporters Discuss the March
Panel Discussion on the Implications of the Freedom March [2 of 2]
```

Those images should all be under the photographs tab in the exhibit page, minus this one, http://openvault.wgbh.org/catalog/openvault:44536
Those images were never related in xml to March on Washington, they were just linked via the exhibit page.

For the audio, there are actually 27 records:
http://openvault.wgbh.org/catalog?f%5Bmedia_sim%5D%5B%5D=Audio&q=March+on+Washington&utf8=✓

**Comment by Muraszko** [comment]
@mccalluc 
For Tab **ERN's coverage of the March on Washington for Jobs and Freedom**
[Use These Audio Records (17)](http://openvault.wgbh.org/catalog?f%5Bmedia_sim%5D%5B%5D=Audio&q=march+on+washintgon+Part&utf8=✓)

For Tab **Revisiting the March on Washington**
[Use These Audio Records (7)](http://openvault.wgbh.org/catalog?utf8=✓&f%5Bmedia_sim%5D%5B%5D=Audio&utf8=✓&q=march+on+washintgon+Interview)

For Tab **Photographs**
[Use These Image Records (17)](http://openvault.wgbh.org/catalog?f%5Bmedia_sim%5D%5B%5D=Image&q=March+on+washington+images+Photograph1&utf8=✓)
