### ISSUE TITLE
Pages not displaying multiple descriptions

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1147]
Some video records have multiple descriptions but are only displaying a single one.
[For Example](http://openvault.wgbh.org/catalog/openvault:42578)
Is displaying 
```
<pbcoreDescription descriptionType="Description">
When you prepare asparagus the French way, you have more of it to eat, it cooks faster, stays greener and tastes fresh from the garden. Delicious plain or served with a buttery orange sauce for a change, and most unusual in a soup, custard, or a quiche.
</pbcoreDescription>
```

But there is an additional description found in the PBCore:
```
<pbcoreDescription descriptionType="Description">
The show opens with Child glowing over how much she appreciates asparagus and giving viewers advice about how to judge, purchase, and store it. Child emphasizes the importance of preparing asparagus the French waycutting off only a small amount of the bottom and especially peeling the stalk--asserting that it results in using more of the asparagus, makes it easier to cook and eat, and results in fresher-tasting finished asparagus. She instructs viewers in how to peel the asparagus (using a French vegetable peeler), then tie it into bundles and cook it in boiling water. Although she is clear that it can be served simply with only some lemon juice and salt to flavor it, she prepares a sauce maltese, which consists of hollandaise sauce with orange flavoring. She demonstrates how to beat eggs yolks, juice and other ingredients over heat until they become a custard, then adds melted butter orange flavoring. She describes serving and preparation for asparagus that is to be served cold as well as warm. Finally, she demonstrates how it can be served and eaten. Throughout the episode, and especially in the final scenes, Child stresses the exceptional taste of asparagus, the benefits of cooking it as the French do, and her intense enjoyment of it. She points out that people might eat asparagus every day when it is in season, so having a sauce helps to vary it. She also encourages viewers to serve it on its own as a first course or as a substitute for a salad course. Finally, she concludes by leaning back and lowering a whole stalk into her mouth. Summary and select metadata for this record was submitted by Tracey Deutsch.
</pbcoreDescription>
```

I would like to display both, even if one of them is displayed with the additional metadata under the *Show Details*.

**Done When**
Records with multiple <pbcoreDescription descriptionType="Description"> are displaying on a page.

**Comment by mccalluc** [comment]
@Muraszko : this behavior is changing with #1146: We need to articulate more clearly what the desired behavior is:
- As far as the UI goes, is there one description for an asset, or multiple? (I would prefer one, since I think multiple will only make our lives harder.)
- What is that description? A concatenation of all the descriptions? Does the order or formatting matter? The "best" one?

I would suggest grepping our fixtures just to get some sense of the variety out there, but there are of course cases we haven't yet put in the tests.

**Comment by Muraszko** [comment]
@mccalluc 
Sometimes the descriptions are from MARS, sometimes they are taken from original broadcast material, sometimes they are curated by scholars or staff in the MLA.  

For cases like this, should I just structure new PBCore with a single <pbcoreDescription descriptionType="Description"> and let you guys re-ingest? Rather than try and modify the page structure for a few exceptions?

**Comment by Muraszko** [comment]
I will modify the PBCore and submit to you guys to re-ingest.

**Comment by Muraszko** [comment]
@afred @mccalluc 
Please find the modified, combined <pbcoreDescription> xml files here:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Mellon_2013/January_Fixes/French_Chef_smoosh_descriptions

The prefix of the file names is the UOI_ID.

**Done When**
- Those three files get ingested
- They overwrite the current pbcore data on the records
- Confirm they look good on the page

**Comment by Muraszko** [comment]
Checked, everything looks good.  Confirm that grabbing the URL.pbcore xml and modifying that is a good way to edit the metadata.
Closing.
