### ISSUE TITLE
March on Washington transcripts not displaying

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1148]
The audio from the March on Washington series looks like it [should have transcripts attached](http://deprecated.openvault.wgbh.org/catalog?f%5Bpbcore_pbcoreTitle_series_s%5D%5B%5D=March+on+Washington&q=part+2+of+17&search_field=all_fields&utf8=✓&x=11&y=2).

[Checking the PBCore on current Open Vault for a record](http://openvault.wgbh.org/catalog/march-4129a4-panel-discussion-on-the-implications-of-the-freedom-march-1-of-2.pbcore)
It has the relation
```
<pbcoreRelation>
<pbcoreRelationType source="LINK_TYPE" annotation="Current item is the source of this relationship">CONTAINS</pbcoreRelationType>
<pbcoreRelationIdentifier source="UOI_ID" annotation="Another item is the destination of this relationship">59cec533398ff702d411e3669754e73d85969a16</pbcoreRelationIdentifier>
</pbcoreRelation>
```
That is the UOI_ID for:
**barcode111476_transcript_smil.xml** Is that file found anywhere on the server?

**Comment by mccalluc** [comment]
Yes: this exists:
```
/wgbh/http/openvault/ingest_data/transcripts/all_transcripts/barcode111476_transcript_smil.xml
```

**Comment by Muraszko** [comment]
Closing, this was fixed with the recent re-ingest.
