### ISSUE TITLE
Modify Eric in the Evening double descriptions

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1155]
Waiting on #1147 to close to make sure the process for getting the PBCore for the records is a valid way of modifying the xml.

Metadata for the audio records for Eric in the Evening have double <pbcoreDescription>.  @muraszko will modify the xml files to only contain a single one.

**Done When**
- The files have been modified
- They are ingested into Open Vault and overwrite the current PBCore records
- They are checked and confirmed they look good on the site

**Comment by Muraszko** [comment]
@afred 
Here is the location of the Eric in the Evening PBCore xml files to please ingest just like the French Chef ones:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Mellon_2013/January_Fixes/Eric_Evening_smoosh_descriptions

**Comment by afred** [comment]
i don't recall doing this explicitly.. but I checked the records in the repository, and none currently have double descriptions. Fixed by re-ingest maybe? Closing.

**Comment by Muraszko** [comment]
@afred 
Re-opening, there are[ double descriptions](http://openvault.wgbh.org/catalog/fa0523-eric-in-the-evening-art-taylor-interview.pbcore), I made new PBCore found above.  The records on the site now have the tag <pbcoreDescription descriptionType="Summary3"> so the new PBCore fixes that to <pbcoreDescription descriptionType="Description">

**Comment by afred** [comment]
Ah... my bad. I was looking at `locations_by_type` from the rails console, which clobbers one of the two descriptions. Reingesting asap... stand by.

**Comment by afred** [comment]
@Muraszko re-ingested and re-slugged.. so should be working. Please check it out and close if so. thanks
