### ISSUE TITLE
Modify many records with double <pbcoreDescription>

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1156]
See #1155 and #1147 

- Sense of Poetry
- Prospects of Mankind
- [Psycoanalysis](http://openvault.wgbh.org/catalog/openvault:54958)
- [Wrath of Achilles](http://openvault.wgbh.org/catalog?f%5Bmedia_sim%5D%5B%5D=Video&q=wrath+of+achilles&utf8=✓)
- [Joyce Chen Cooks](http://openvault.wgbh.org/catalog?f%5Bmedia_sim%5D%5B%5D=Video&q=joyce+chen+cooks&utf8=✓)

**Comment by Muraszko** [comment]
You can find the corrected PBCore xml files here:

-Sense of Poetry

-Prospects of Mankind

-Psychoanalysis
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Mellon_2013/January_Fixes/PSYCHOANALYSIS

-Wrath of Achilles

-Joyce Chen Cooks

**Comment by afred** [comment]
@Muraszko spot checking some of these.. looks like double description issue may have gotten resolved? Confirm?

**Comment by Muraszko** [comment]
@afred 
Joyce Chen and Prospects of Mankind are good, you'll need to update OV records with new PBCore for:
**-Psychoanalysis**
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Mellon_2013/January_Fixes/PSYCHOANALYSIS
**-Eric in the Evening** #1155 
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Mellon_2013/January_Fixes/Eric_Evening_smoosh_descriptions

I still have to generate some PBCore for:
-Sense of Poetry
-Wrath of Achilles
I'll make a new ticket for these two when I can do that.

**Comment by afred** [comment]
@Muraszko check on Psychoanalysis here: http://openvault.wgbh.org/catalog/e731ef-psychoanalysis-a-personal-view. Close if looks good? Make new tickets for the rest?

**Comment by Muraszko** [comment]
Looks good.  I'll make a new ticket for the remaining when I have the xml.
