### ISSUE TITLE
Create Advocates Exhibit Page List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1162]
@afred 
.. from UOI_IDs list found here:

Rename the Video tab, "Full Program Video"

smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Advocates_UOIDs/Advocates_UOI_IDs.csv

**Comment by afred** [comment]
@Muraszko get rid of the "Program" tab then? Seems redundant.

**Comment by Muraszko** [comment]
@afred 
:+1: for removal of Program tab

**Comment by afred** [comment]
closed by #1197
