### ISSUE TITLE
Modify Nuclear Age Exhibit Page List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1163]
@afred 
Please change and add a tab to the Nuclear Age exhibit page.

Rename VIDEOS tab to "Original Footage"
Use this list of UOI_IDs to populate the list:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Nukes_UOIDs/B_roll_uoi_ids.csv

Add another tab called, "Stock Footage"
Use this list of UOI_IDs to populate the list:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Nukes_UOIDs/stock_footage_uoi_ids.csv

Thanks!

**Comment by afred** [comment]
@Muraszko so the final tabs will be:
"Interviews" | "Original Footage" | "Programs" | "Stock Footage"
?

**Comment by Muraszko** [comment]
@afred 
Yes please.

**Comment by afred** [comment]
closed by #1195. @Muraszko check it out on [staging(]http://openvault-staging.wgbh.org/catalog/wpna-wpna-war-and-peace-in-the-nuclear-age#Programs), and when you :+1: I will deploy to production.

**Comment by Muraszko** [comment]
:+1: Looks great Drew.  I see #1196 and once that's deployed too, that'll be perfect.
