### ISSUE TITLE
Create Rock and Roll Exhibit List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1164]
@afred 
Please populate the Rock and Roll Exhibit page tabs with the following.

Under tab, "Interviews"  find the UOI_IDs list here:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Rock_UOIDs/Rock_UOI_IDs.csv

Remove "Videos" Tab

Under tab, "Programs" please populate with list of programs from Rock and Roll series:
http://openvault.wgbh.org/catalog/changeme:3017

**Comment by afred** [comment]
(hopefully) closed by #1193. @Muraszko take a peek and close this ticket if it looks alright. Please and thankyou.

**Comment by Muraszko** [comment]
@afred 
Getting "The page you were looking for doesn't exist" error on live site and staging site Rock and Roll collection page.

**Comment by afred** [comment]
what url are you using?
