### ISSUE TITLE
Update Press and the People Exhibit Page List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1165]
Change the Media tab to "Full Program Video"
Find the UOI_IDs list here:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Press_People_UOIDs/Press_People_UOIDs.csv

**Comment by afred** [comment]
closed by #1168.

**Comment by afred** [comment]
reopened due to comprehensieve re-ingest

**Comment by afred** [comment]
closing as this should be fixed by #1170.
