### ISSUE TITLE
Update Say Brother Exhibit Page List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1166]
You can keep the "Video" tab since most of the Say Brother video is only clips, not whole programs.

You can find the list of Say Brother UOI_IDs here:

smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Say_Brother_UOIDs/Say_Brother_UOIDs.csv

**Comment by afred** [comment]
@Muraszko I don't have source files for any of these Say Brother UOI_IDs.

**Comment by afred** [comment]
^^ and the only Say Brother records that have been ingested appear to have either come from MARS or from Old Openvault directly. [Here is a list](https://gist.github.com/afred/40f5979ace7416c0d051).

**Comment by afred** [comment]
@Muraszko did we figure out where these source xml files are?

**Comment by Muraszko** [comment]
Since the majority of the Say Brother records come from deprecated.openvault's rogue records, and that has lead to trouble in the past, for the time being I linked the homepage carrousel to a canned search for "Say Brother".  I'm fine with this as a temporary solution until I have time to generate some new PBCore XML for you.  If you want to close this for now, I'm ok with that.

**Comment by afred** [comment]
Right on. Closing.
