### ISSUE TITLE
Press and People videos are not playing (missing?)

### ISSUE THREAD

**Issue by afred** [afred/openvault#1170]
Go here: http://openvault.wgbh.org/catalog/prpe-press-and-the-people
and these videos aren't playing.
![image](https://cloud.githubusercontent.com/assets/1507490/5877739/b44c1580-a2ef-11e4-8c49-a04a9f23376b.png)

**done when**
those videos play, like the first 4 do.

**Comment by Muraszko** [comment]
I think some of these records are looking for the video on the server based off the wrong PBCore field.

Currently, [this record for example](http://openvault.wgbh.org/catalog/openvault:58540) is looking for:
http://mlamedia01.wgbh.org/openvault/video/Complete%20Video1726

So it's pointing to this field in the PBCore:
```
<instantiationIdentifier source="Original file name" version="1" annotation="ArtesiaDAM user ID: 1 imported 2008-06-11 16:55:52.0">Complete Video1726</instantiationIdentifier>
```

Should I edit the PBCore in that field to reflect the actual filename?

**Comment by afred** [comment]
@Muraszko ^^ yes please! Sorry it took so long to respond here.

**Comment by Muraszko** [comment]
@afred 
Edited Press and the People XML:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/Press_People_Updated_XML

16 updated video XML files and one updated image XML file because it was looking for a .pct file, which was causing it to not load on the page.

**Comment by afred** [comment]
awesome! reingesting.. stand by.

**Comment by afred** [comment]
Done. @Muraszko confirm and close ticket when you get a chance please?

**Comment by afred** [comment]
oh.. btw.. use staging site at http://openvault-staging.wgbh.org/catalog/prpe-press-and-the-people

**Comment by Muraszko** [comment]
Looks good.  Thank you!
