### ISSUE TITLE
Missing Series and Program Records

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1177]
Looks like a bunch of series and program records are missing while I'm browsing around Open Vault:

http://openvault.wgbh.org/series
No Frontline, Arthur, ect.

Also, when doing a search for Fronline programs:
http://openvault.wgbh.org/catalog?f%5Bhas_model_ssim%5D%5B%5D=Program&q=Frontline&utf8=✓

Did records get removed from Solr or something?

**Comment by afred** [comment]
^^ for the 2nd issue mentioned above.. see #1180.

**Comment by afred** [comment]
@Muraszko I think the fresh repo may have fixed the first part? If it looks like it, please close this ticket (the second part is covered in #1180).

**Comment by Muraszko** [comment]
Looks good to me.  Thanks.
