### ISSUE TITLE
Facets for the `has_model_ssim` field are not using the right values.

### ISSUE THREAD

**Issue by afred** [afred/openvault#1180]
**done when**
  - [ ] Facets for the `has_model_ssim` field display value and count correctly (this is already working -- just make sure it doesn't get broken).
  - [ ] clicking the facet returns the expected results
  - [ ] Label for facet-off buttons (top of screen when facet is activated) do not have the gobbly-gooky text, but rather the user-friendlier text that displays in the facet-on buttons (left side bar). 

**Yes**
![image](https://cloud.githubusercontent.com/assets/1507490/6031415/1f230b3a-abcd-11e4-8ad1-1a03726efb1c.png)

**No**
![image](https://cloud.githubusercontent.com/assets/1507490/6031406/08480154-abcd-11e4-8ce7-d49527e4e541.png)

**Background info.**
Each solr document contains a field called `has_model_ssim`, created by Hydra (under the hood) that stores the class name that was used to save the record. Example: "info:fedora/afmodel:Program". The thing we are interested in here is "Program", however Hydra tacks on that other stuff for reasons unknown.

The facet is broken because it is only searching part of the string, e.g. it only returns documents where `has_model_ssim` field contains "Program" (of which [there are 0](http://openvault.wgbh.org/catalog?f%5Bhas_model_ssim%5D%5B%5D=Program&q=Frontline&utf8=%E2%9C%93)), instead of searching for documents where the `has_model_ssim` field contains "info:fedora/afmodel:Program" (of which [there are 544](http://openvault.wgbh.org/catalog?f%5Bhas_model_ssim%5D%5B%5D=info%3Afedora%2Fafmodel%3AProgram&q=Frontline&utf8=%E2%9C%93)).

So why did it break when it was working before?

Because we changed something. There used to be a field called `media_sim` that contained the meaningful class name, e.g. "Program", and that was the field the facet was using (i think). However, we were running into issues where it differed from the less user-friendly `has_model_ssim` field. So @mccalluc and I agreed that we didn't really need two different fields to do the same thing, and we could just use the one that Hydra gives us for free, `has_model_ssim`.

But.. apparently we're missing some test coverage here, because it appears to have broken these facets without our knowing.

The facet count on the right is displaying the correct count of records, so I'm guessing there is a way to make this work

**Comment by Muraszko** [comment]
Thanks for the explanation.
-Mike

**Comment by mccalluc** [comment]
The earlier work I did was under #1152: Do we know whether the problem goes back to that, or if it's a regression since then?

**Comment by afred** [comment]
^^ @mccalluc yeah i think it was [changing this line](https://github.com/afred/openvault/pull/1158/files#diff-956e46b33fb5307990c4e1a4b5fd86ccL88) that did it.

Then, we make the sidebar facet control strip out the "info:fedora/afmodel" part of the facet values with [this line](https://github.com/afred/openvault/pull/1158/files#diff-589af095737c1f1e569c7a172a530eb7R21).

The trick will be to have sidebar facet-on control (sidebar, and the facet-off control (above search results) to display the values with "info:fedora/afmodel" stripped out, while still using the full facet value in the call to Solr. Not sure how easy it is to intercept Blacklight's facet behavior to do that. If it's easy, I'd prefer to do it. But if its not, then we can revert the commit and reindex records, knowing now that `media_sim` did in fact _not_ do the same thing as `has_model_ssim`, like we originally thought.

**Comment by afred** [comment]
fixed by #1183
