### ISSUE TITLE
Some transcripts are related to the Series record for Vietnam instead of the video.

### ISSUE THREAD

**Issue by afred** [afred/openvault#1188]
**Done when**
  - ~~We've identified the videos for these transcripts~~ **EDIT:** No videos found for these transcripts. 
  - ~~Source metadata corrected and uploaded to production server~~ **EDIT:** Nothing to do b/c no videos.
  - ~~Re-ingested and verified correct relationships~~ **EDIT:** Nothing to do b/c no videos
  -  [x] Ingest the one video for Advocates: "Should The Government Drop The Charges Against Daniel Ellsberg"

Here's a gist of all the metadata for the transcripts.
https://gist.github.com/afred/5ea66cf91b2476849410

**Comment by afred** [comment]
@Muraszko 

I found 11 transcripts that were not related to a Video or a Program. See gist in the ticket description.

10 of these Transcript objects are related directly to the Vietnam series record, instead of the individual video records that they should be related to.

1 of these Transcript records (id=openvault:1423) is said to belong to an Advocates video, that I currently have in the "do not release to openvault" bucket -- however looking at the metadata, it says: "Video can be released to Open Vault, but only as the condition that the trail for the Attica program is removed from the web version". Do we know where that stands?

**Comment by Muraszko** [comment]
@afred 
The 10 without video are probably transcript only records, no video proxy files so they would only be related to the series.

The one transcript from Advocates, it was part of the Vietnam collection, even though it was from the Advocates.  If it were on Open Vault, here is the Artesia UOI_ID: 
```
fd262c46203688fabd4ec7deda6f9121b4903d38
```

The movie file itself should be:
barcode121019-1.mov or something like that.

**Comment by afred** [comment]
@Muraszko So is it ok then, to just let these Transcript records not be discoverable/viewable on openvault? Currently, we only display Transcripts if they are tied to a video.

For the Advocates transcript: "Should The Government Drop The Charges Against Daniel Ellsberg" here's the situation:
  1. we have a MARS record for it that has been ingested: http://openvault.wgbh.org/catalog/openvault:12921
  1. the Transcript record has also been ingested, as noted above.
  1. the Video record from Artesia has _not_ yet been ingested yet, because it is in the "Do Not Ingest to Openvault" directory on the production server, because of the rights restriction mentioned above.

So.. .can I ingest the video? Or should it stay off the website?

**Comment by Muraszko** [comment]
Vietnam transcripts: 
So you can't just leave a transcript only page looking like this one?
http://openvault.wgbh.org/catalog/openvault:1423
Those specific transcript only records should be viewable.

Advocates video: Please ingest video and ignore the "Do not ingest" text because it has been edited and is safe to publish.
Thanks.

**Comment by afred** [comment]
re: vietnam...
Ah.. yes. I forgot you can view Transcripts like that. However, I think we leave them out of search results on purpose, because it's a little confusing for all of the Transcripts that _are_ tied to videos, and are displayed on the Video page. So right now, those 10 Transcript records are viewable, but not really searchable. Not sure how easy it would be to make exceptions for those 10. Low priority?

re: advocates...
ok.. will ingest.

**Comment by afred** [comment]
Done.
![image](https://cloud.githubusercontent.com/assets/1507490/6401165/78261a90-bdcc-11e4-9962-89a2907dc890.png)
