### ISSUE TITLE
Missing Press and People video?

### ISSUE THREAD

**Issue by afred** [afred/openvault#1191]
@Muraszko There is one of the Press and People UOI_IDs for which I can't find source metadata (coming from the list on dept server).

`492c1653779e2970c26ab5ebb0e56774a9eb91d6`

Can't remember if we've run into this one before or not.

**Comment by Muraszko** [comment]
@afred 
Weird, that UOI_IDs is for a clip from this program [already on Open Vault](http://openvault.wgbh.org/catalog/3f0d6c-bomb-and-the-press-the).

That UOI_IDs must have gotten accidentally exported from DAM, sorry!  
It's ok to omit it.
