### ISSUE TITLE
Busted ass exhibit page links

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1192]
Some of the exhibit pages have busted links since the re-ingest.  
Looks like links hardcoded with the **/catalog/openvault:** URLs are now, as expected, are broken.
It's easy enough to fix because the titles should be searchable, then you can just grab the updated URL (Or some other value less likely to break if we have to re-ingest)

**DONE WHEN**
Exhibit pages that had links to **/catalog/openvault:** pages are working again.

**Comment by Muraszko** [comment]
If it helps to rebuild this list for the busted links, remember there are lists of UOI_IDs on the server:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload

**Comment by afred** [comment]
there are still open tickets for individual collections. Working those currently.. .stand by.

**Comment by afred** [comment]
So.. i think these have all been taken care of. Closing.. but double check me @Muraszko and re-open it if I goofed.
