### ISSUE TITLE
PBCore Corrections

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1211]
@afred 
Here's the remaining PBCore I was talking about in #1156 

Please re-ingest the xml in these two folders:
**Sense of Poetry**
/Volumes/dept/MLA/OpenVault_Upload/Mach_2015_Fixes

**Wrath of Achilles**
/Volumes/dept/MLA/OpenVault_Upload/Mach_2015_Fixes

**Comment by afred** [comment]
Re-ingested and re-slugged. @Muraszko double check and close?
