### ISSUE TITLE
Modify March on Washington exhibit page

### ISSUE THREAD

**Issue by afred** [afred/openvault#1216]
**done when**
March on Washington exhibit page includes the link: [March on Washington Listeners Guide](http://blog.openvault.wgbh.org/2013/08/march-on-washington-listeners-guide) listed first under "Related Links"

**Comment by mccalluc** [comment]
This was done in 27103409, just needs to be deployed.

**Comment by afred** [comment]
@Muraszko sorry thought I had deployed that already. But must have done so locally, or on staging only.
