### ISSUE TITLE
Missing Transcripts

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1221]
Some Machine that Changed the World interviews are missing their transcripts from their record pages.
These were displaying correctly in the past month or two, not sure why they have disappeared.

[Alan Kay](http://openvault.wgbh.org/catalog/5ec39a-the-machine-that-changed-the-world-interview-with-alan-kay-1990)
[Mitch Kapor](http://openvault.wgbh.org/catalog/db056f-the-machine-that-changed-the-world-interview-with-mitch-kapor-1990)
[Larry Tesler](http://openvault.wgbh.org/catalog/7482b2-the-machine-that-changed-the-world-interview-with-larry-tesler-1992)
[Paul Ceruzzi](http://openvault.wgbh.org/catalog/2eb7b8-the-machine-that-changed-the-world-interview-with-paul-ceruzzi-1991)
[Robert Lucky](http://openvault.wgbh.org/catalog/63d948-the-machine-that-changed-the-world-interview-with-robert-lucky)
[Ted Nelson](http://openvault.wgbh.org/catalog/326388-the-machine-that-changed-the-world-interview-with-ted-nelson-1990)

**DONE WHEN**
Those six record pages are displaying their transcripts.

**Comment by mccalluc** [comment]
most worked, but these didn't: 
- Mitch Kapor
- Larry Tesler (link above is wrong)

Need to look into these two.

**Comment by mccalluc** [comment]
Tesler is fixed.

**Comment by mccalluc** [comment]
@afred: I can't seem to find the metadata record for Kapor:
```
$ grep 'Kapor' -lr /wgbh/http/openvault/openvault_ingest_data/pbcore_xml_from_artesia/all_assets/ | xargs less
```
There are four files that match: a Video, Image, Program, and Series, but no Transcript. Thoughts?

**Comment by afred** [comment]
check in this directory: `/wgbh/http/openvault/ingest_data/pbcore_xml_from_artesia/do_not_put_on_openvault/`

this is a place where I dumped a lot of records that weren't to be released to openvault. The way you can tell if a record is not to be released to OV, is by some user-entered text that says somethign to that effect. It is mostly the same message, and I think it's mostly in the same xpath, but not always.

If the transcript isn't in that directory.. then we don't have it... ask @Muraszko.

**Comment by mccalluc** [comment]
No results for
```
grep kapor -irl /wgbh/http/openvault/ingest_data/pbcore_xml_from_artesia/do_not_put_on_openvault/
```
@Muraszko : unable to locate the Kapor metadata. I think it's just a pointer to the the transcript text, so maybe we create one from scratch?

**Comment by Muraszko** [comment]
@mccalluc @afred 
Sorry guys, just looked back on some old emails.  Mitch Kapor was an interview we didn't have a transcript made for.  So this issue is good to close.  Sorry for the confusion.  Thanks the fixing the others.
