### ISSUE TITLE
Credits Page Wrong URL

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1223]
[The Credits page seems to be broken.](http://openvault.wgbh.org/credits/)
It's listed on the website footer too.

The Credits page is actually [this](http://openvault.wgbh.org/credits/credits):
```
http://openvault.wgbh.org/credits/credits
```

**DONE WHEN***
http://openvault.wgbh.org/credits/ redirects to http://openvault.wgbh.org/credits/credits
Unless you feel it's better to fix the page: /credits/credits URL to just /credits

**Comment by Muraszko** [comment]
@afred I'm not seeing the changes for this on the site, could you please deploy when you get a chance?  Thanks.

**Comment by afred** [comment]
@Muraszko deploying to staging, since it's a visual change, let's verify on http://openvault-staging.wgbh.org first.

**Comment by Muraszko** [comment]
Looks good to me.  Thanks guys, feel free to push to the live site.

**Comment by afred** [comment]
on it's way.. check in 5.

**Comment by Muraszko** [comment]
Thanks Drew, all set.
