### ISSUE TITLE
Update Sadie's xml template for clips

### ISSUE THREAD

**Issue by mccalluc** [afred/openvault#1225]
Follow-up from #1219:

Tweaking the titleType in the xml allowed the classifier to work:
```xml
  <pbcoreTitle titleType="Clip">Al Jarreau performs "You Don't See Me"</pbcoreTitle>
```

Can this change be made in the original template?
(Should the template be under version control?)

**Comment by afred** [comment]
I went ahead and tweaked the classifier to identify videos when the pbcore asset type is "Clip". I didn't see this ticket until just now.

+1 for putting templates in version control. @sroosa Can you send me the templates you're using? I'll put them in Stash with the OV ingest data.

**Comment by afred** [comment]
Added templates to Stash: https://atlas.wgbh.org/stash/projects/MLA/repos/openvault_ingest_data/browse/pbcore_templates

closing
