### ISSUE TITLE
Ingest single XML Program record

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1226]
To update an existing MARS exported program record.

**DONE WHEN**
openvault_23798.pbcore.xml (sent via email) is successfully ingested, updated and displaying correctly into Open Vault.

**Comment by afred** [comment]
just a note on terms in regards to ingesting with Openvault:
  * **replace** means the original Fedora object will be deleted, and a new one will be created, with a new Fedora ID. If the original record is referred to by anything else, then that reference will be broken after the ingest.
  * **update** means the original Fedora object is _not_ deleted, so the Fedora ID will be the same and referential integrity will be preserved. However, the entire XML datastream will be updated with new XML.

From the outside, it's tempting to think of the PBCore XML source files as _the record_. But in reality, the XML is just _one part_ of a larger Fedora record.

**Comment by mccalluc** [comment]
Done, but
- This takes me about 20 minutes, from start to finish, and there is no value that I add.
- Our indexing isn't actually picking up the new subject terms: "Master Cylinder" is listed on http://openvault.wgbh.org/catalog/openvault:23798, but pulls back no results on http://openvault.wgbh.org/catalog?utf8=%E2%9C%93&q=Master+Cylinder
