### ISSUE TITLE
Update Say Brother Exhibit Page List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1227]
When #1215 is closed, please update the [exhibit page for Say Brother](http://openvault.wgbh.org/catalog/sbro-say-brother) to appear like the [other Exhibit pages.](http://openvault.wgbh.org/collections/vietnam)

The tabs should be:
**Complete Collection**
With records populated from this list:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/IDs_in_each_collection/Say_Brother_Complete_Collection.csv

**Civil Rights Collection**
With records populated from this list:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/IDs_in_each_collection/Say_Brother_Civil_Rights.csv

**Music Performances**
With records populated from this list:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/IDs_in_each_collection/Say_Brother_Music_Performances.csv

**Comment by afred** [comment]
closed by #1232.

@sroosa can you double check that I got the right links listed under the right tabs? Some of the record descriptions under Music Performances don't describe any performance, but an entire program.

**Comment by sroosa** [comment]
@afred yeah, they're right. I just used the same subcollections that were on deprecated OV. I think they fall under there because there is a music performance in the program somewhere.
