### ISSUE TITLE
Update NTW Exhibit Page List

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1228]
When #1215 is closed, please update the [exhibit page for NTW](http://openvault.wgbh.org/collections/new-television-workshop) to appear like the [other Exhibit pages.](http://openvault.wgbh.org/collections/vietnam)

The tabs should be populated as below.

**Complete Collection**
With records populated from this list:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/IDs_in_each_collection/NTW_Complete_Collection.csv

**Artist's Showcase**
With records populated from this list:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/IDs_in_each_collection/NTW_Artists_Showcase.csv

**Frames of Reference**
With records populated from this list:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/IDs_in_each_collection/NTW_Frames_of_Reference.csv

**Comment by Muraszko** [comment]
The New Television Workshop at WGBH supported the creation and broadcast of experimental works by artists from 1974 to 1993. The New Television Workshop Collection was preserved, arranged, and described by the WGBH Media Library and Archives with support from the National Endowment for the Arts (Grant # A 96 – 019016). Materials in the collection include videos from the New Television Workshop, as well as early video arts works that pre-dated organization of the New Television Workshop and ancillary but related video art works produced by WGBH.


Search within this collection
		All materials
		All Artists's Showcase materials
		All Frames of Reference materials

Related links
		New Television Workshop Finding Aid
		New Television Workshop Exhibit Space
		Learn about the influence of NTW on experimental art
Funding provided by The National Endowment for the Arts
￼

```

**Comment by afred** [comment]
done
http://openvault.wgbh.org/collections/new-television-workshop

**Comment by Muraszko** [comment]
@afred 
Thanks Drew, that looks great.  I did notice that one of the links on the exhibit page is broken, they must have updated their website.  Could you please replace the link to:

**Learn about the influence of NTW on experimental art**
with 
http://forum-network.org/lectures/history-experimental-video-boston/

Thanks
