### ISSUE TITLE
Ingest Studio Talk mp3 and XML record

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1229]
I have another custom created XML file to ingest.  It's related to the mp3 file in the folder, it's an audio record.

smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/April_2015_Ingest/Studio_Talk

**DONE WHEN**
The xml file is ingested and the record and mp3 file are displaying on the live, Open Vaut website.

**Comment by afred** [comment]
done

http://openvault.wgbh.org/catalog/openvault:44169
