### ISSUE TITLE
Link for "Production Research Footage Database" is unusable on mac/ff

### ISSUE THREAD

**Issue by mccalluc** [afred/openvault#625]
On http://openvault.wgbh.org/collections/vietnam-the-vietnam-collection, the popup that you get by clicking "Production Research Footage Database" is unusable, at least for me: we've somehow styled it so that there is no scrollbar, and you can't get to the link.

(If you just go to the url directly it's fine, so let's just do that.)
(I'm not sure how usable this database export is: I really can't imagine anyone just scrolling through the records. If we want it to be public, could we just post a CSV?)

**Comment by Muraszko** [comment]
@afred 
Could you please put this back in the original footage tab of the Vietnam exhibit page?  Or on with the static "Related links"

Here is what the code looked like on the deprecated.openvault
```
<li><script type="text/javascript">
function browseSFDB(){
window.open ("http://openvault.wgbh.org/sfdb/about/intro.html", "dbviewer", "status=0,menubar=0,toolbar=0,width=575")
}
</script><br />
<a href="#" onClick="browseSFDB()">Production Research Footage Database</a></li>
```

**Comment by afred** [comment]
Ah.. yeah. I see it in the code, but it got lost in the shuffle. Should it appear at the top of the list of "Original Footage", or at the bottom?

**Comment by Muraszko** [comment]
Yeah, sorry, I should have mentioned I wanted to keep it.  Top of the list would be fine.
Thank you.

**Comment by Muraszko** [comment]
Checked on live site, looks good close if it's good on your end.
