### ISSUE TITLE
Transcripts not showing up for things that should have them

### ISSUE THREAD

**Issue by afred** [afred/openvault#752]
On lsopenvault01.wgbh.og

![image](https://cloud.githubusercontent.com/assets/1507490/4380727/fadef64e-436c-11e4-886e-0f204c01e234.png)

And on splat...

![image](https://cloud.githubusercontent.com/assets/1507490/4380754/1dc821a8-436d-11e4-88be-17d84e8510c2.png)

**Done when**
  - [x] we know what's going on (leave a comment)
  - [ ] all affected records are fixed.

**Comment by Muraszko** [comment]
[Also relating to this record (and others):](http://openvault.wgbh.org/catalog/wpna-35670b-interview-with-leslie-gelb-1987)

[The correct record](http://openvault.wgbh.org/catalog/openvault:52960)

**Comment by afred** [comment]
Closing. This appears to have been resolved after full re-ingest of all records and transcripts.

If the more examples are found, please create a new ticket to keep the convo more concise.
