### ISSUE TITLE
"Programs in this Series" looks bad when a program doesn't have an episode number

### ISSUE THREAD

**Issue by avatousiou** [afred/openvault#822]
The space is just empty when a program doesn't have an episode number on the series show page making it look weird when only some of them have numbers and broken when none of them do

(For example: http://openvault.wgbh.org/catalog/changeme:2517)

**Comment by mccalluc** [comment]
@Muraszko: This did regress with the tabs. It felt more important to get that out, at the cost of losing the special treatment for Programs we had had formerly. I'll see if it can be reincorporated.

**Comment by Muraszko** [comment]
@mccalluc Thank you.
