### ISSUE TITLE
Citation information migration

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#992]
Karen pointed out on deprecated.openvault that the CITE data on each record page needs to be migrated over.
She mentioned Zotero:
https://www.zotero.org/

I don't know if the CITE specific link is an API or what, but it looks like Zotero is a browser plugin to let researchers easily add citation information to their papers. I don't know how best to expose citation data, should we just leave that to applications like Zotero?  Either way, she wants to address things that were present on deprecated.openvault that are no longer there, for better or worse.

**Comment by Muraszko** [comment]
@mccalluc This looks ready to close, right?

**Comment by mccalluc** [comment]
@Muraszko: UI is there (might check that it's not too ugly), but haven't touched API, so, no, not quite.

**Comment by Muraszko** [comment]
May not need the Zotero API ties, Karen is checking, if we don't need the Zotero stuff, this is good to close.  Stand by.
